/*DROP TABLE IF EXISTS USUARIO;  
CREATE TABLE USUARIO (  
id INT PRIMARY KEY NOT NULL,
ts_creacion TIMESTAMP DEFAULT(NOW())NOT NULL,
name VARCHAR(300) NOT NULL,
email VARCHAR(150) NOT NULL,
password VARCHAR(150) NOT NULL,
estado BOOLEAN NULL,
token_acceso VARCHAR(150) NOT NULL,
ts_modificacion TIMESTAMP NULL,
ultima_conexion TIMESTAMP NULL,
);
DROP TABLE IF EXISTS TELEFONO;  
CREATE TABLE TELEFONO (  
id INT AUTO_INCREMENT  PRIMARY KEY,
id_usuario INT NOT NULL,
phone VARCHAR(300) NOT NULL,
citycode VARCHAR(50) NOT NULL,
contrycode VARCHAR(50) NOT NULL  
);  */