/*DROP TABLE IF EXISTS USUARIO;  
CREATE TABLE USUARIO (  
--id INT AUTO_INCREMENT  PRIMARY KEY,
id INT PRIMARY KEY NOT NULL,
ts_creacion TIMESTAMP DEFAULT(NOW())NOT NULL,
name VARCHAR(300) NOT NULL,
email VARCHAR(150) NOT NULL,
password VARCHAR(150) NOT NULL
);
DROP TABLE IF EXISTS TELEFONO;  
CREATE TABLE TELEFONO (  
--id INT AUTO_INCREMENT  PRIMARY KEY,
id INT NOT NULL PRIMARY KEY,
ts_creacion TIMESTAMP NOT NULL,
id_usuario INT NOT NULL,
phone VARCHAR(300) NOT NULL,
citycode VARCHAR(50) NOT NULL,
contrycode VARCHAR(50) NOT NULL  
);  */